# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zoomcpp/projects/cterm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zoomcpp/projects/cterm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/zoomcpp/projects/cterm && $(CMAKE_COMMAND) -E cmake_progress_start /home/zoomcpp/projects/cterm/CMakeFiles /home/zoomcpp/projects/cterm/libcterm/src/CMakeFiles/progress.marks
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f CMakeFiles/Makefile2 libcterm/src/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zoomcpp/projects/cterm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f CMakeFiles/Makefile2 libcterm/src/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f CMakeFiles/Makefile2 libcterm/src/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f CMakeFiles/Makefile2 libcterm/src/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/zoomcpp/projects/cterm && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
libcterm/src/CMakeFiles/cterm.dir/rule:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f CMakeFiles/Makefile2 libcterm/src/CMakeFiles/cterm.dir/rule
.PHONY : libcterm/src/CMakeFiles/cterm.dir/rule

# Convenience name for target.
cterm: libcterm/src/CMakeFiles/cterm.dir/rule
.PHONY : cterm

# fast build rule for target.
cterm/fast:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/build
.PHONY : cterm/fast

linux_cursor.o: linux_cursor.cpp.o
.PHONY : linux_cursor.o

# target to build an object file
linux_cursor.cpp.o:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_cursor.cpp.o
.PHONY : linux_cursor.cpp.o

linux_cursor.i: linux_cursor.cpp.i
.PHONY : linux_cursor.i

# target to preprocess a source file
linux_cursor.cpp.i:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_cursor.cpp.i
.PHONY : linux_cursor.cpp.i

linux_cursor.s: linux_cursor.cpp.s
.PHONY : linux_cursor.s

# target to generate assembly for a file
linux_cursor.cpp.s:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_cursor.cpp.s
.PHONY : linux_cursor.cpp.s

linux_terminal.o: linux_terminal.cpp.o
.PHONY : linux_terminal.o

# target to build an object file
linux_terminal.cpp.o:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_terminal.cpp.o
.PHONY : linux_terminal.cpp.o

linux_terminal.i: linux_terminal.cpp.i
.PHONY : linux_terminal.i

# target to preprocess a source file
linux_terminal.cpp.i:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_terminal.cpp.i
.PHONY : linux_terminal.cpp.i

linux_terminal.s: linux_terminal.cpp.s
.PHONY : linux_terminal.s

# target to generate assembly for a file
linux_terminal.cpp.s:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_terminal.cpp.s
.PHONY : linux_terminal.cpp.s

linux_window.o: linux_window.cpp.o
.PHONY : linux_window.o

# target to build an object file
linux_window.cpp.o:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_window.cpp.o
.PHONY : linux_window.cpp.o

linux_window.i: linux_window.cpp.i
.PHONY : linux_window.i

# target to preprocess a source file
linux_window.cpp.i:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_window.cpp.i
.PHONY : linux_window.cpp.i

linux_window.s: linux_window.cpp.s
.PHONY : linux_window.s

# target to generate assembly for a file
linux_window.cpp.s:
	cd /home/zoomcpp/projects/cterm && $(MAKE) -f libcterm/src/CMakeFiles/cterm.dir/build.make libcterm/src/CMakeFiles/cterm.dir/linux_window.cpp.s
.PHONY : linux_window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cterm"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... linux_cursor.o"
	@echo "... linux_cursor.i"
	@echo "... linux_cursor.s"
	@echo "... linux_terminal.o"
	@echo "... linux_terminal.i"
	@echo "... linux_terminal.s"
	@echo "... linux_window.o"
	@echo "... linux_window.i"
	@echo "... linux_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/zoomcpp/projects/cterm && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

